// Define your page navigation order here
export const pageOrder = [
  "/patient-characteristics-input",
  "/brca-mutation-status",
  "/endocrine-therapy-benefits",
  "/baseline-risk-recurrence",
  "/risk-assessment-outcome",
  "/endocrine-therapy-pros",
  "/endocrine-therapy-effects",
  "/elevated-risk-recurrence",
  "/role-cdk46-inhibitors",
  "/characteristics-elevated-risk",
  "/monarche-study",
  "/natalee-study",
  "/treatment-durations",
  "/cdk46-inhibitor-eligibility",
  "/abemaciclib-eligibility",
  "/ribociclib-eligibility",
  "/abemaciclib-precautions",
  "/ribociclib-precautions",
  "/monarche-study-results",
  "/monarche-study-results/part-2",
  "/natalee-study-results",
  "/natalee-study-results/part-2",
  "/abemaciclib-side-effects",
  "/ribociclib-side-effects",
  "/abemaciclib-quality-of-life",
  "/ribociclib-quality-of-life",
  "/abemaciclib-care-journey",
  "/ribociclib-care-journey",
  // Add more pages in order as you build them
];
